### ISSUE TITLE
Update CIUS-PT to 2.1.1

### ISSUE THREAD

**Issue by yleider** [phax/phive-rules#11]
Hi,

is it possible to update the CIUS-PT validation to the newer version 2.1.1 (https://www.espap.gov.pt/Documents/servicos/sp_fin/urn_feap.gov.pt_CIUS-PT_schematron.zip)?

BR

**Comment by phax** [comment]
Sure that can be done. Should version 2.0.0 be deprecated than?

**Comment by phax** [comment]
Part of 2.1.10 release soon to be released

**Comment by yleider** [comment]
I think 2.0.0 should be deprecated. In https://www.espap.gov.pt/spfin/normas/Paginas/normas.aspx it is only listed in the history table. Therefore I think this version is historic
