### ISSUE TITLE
SI-UBL 2.0 hotfix 2022 release

### ISSUE THREAD

**Issue by luukth-infosupport** [phax/phive-rules#15]
A hotfix was released on March the 14th [https://github.com/peppolautoriteit-nl/validation/releases/tag/2023-03-14](https://github.com/peppolautoriteit-nl/validation/releases/tag/2023-03-14)

In the changelog they state
> This updated release can be deployed immediately, but will be mandatory as of 2023-03-27.

These are the new versions: 
Updated SI-UBL 2.0 (NLCIUS) to 2.0.3.6
Updated SI-UBL 2.0 (NLCIUS) g-account extension to 1.0.6
Updated NLCIUS-CII to 1.0.3.5

**Comment by phax** [comment]
Thanks for pointing that out. I will tackle it soon

**Comment by phax** [comment]
This is part of the 3.0.2 release
