### ISSUE TITLE
Adding validation for JP PINT urn:fdc:peppol:jp:billing:3.0 (1.0)

### ISSUE THREAD

**Issue by dwillekens** [phax/phive-rules#16]
Can JP PINT 1.0 validation be added in the validation tool? We would need it through webservice but keeping portal in sync would be nice.
To my understanding, rules can be downloaded (see resources bottom left) at https://docs.peppol.eu/poac/jp/pint-jp/
Feel free to come back in case of other questions. Result might be published in peppol-japan channel on Slack 😉
Regards,
Dirk

**Comment by phax** [comment]
Will be part of the 3.0.3 release

**Comment by dwillekens** [comment]
when will 3.0.3 release be operational? where can this be checked in the API request/response? Thx. for adding.

**Comment by phax** [comment]
As soon as possible. I am dependent on my infrastructure guys, to update my own Tomcat :D
