### ISSUE TITLE
Please add the new rules for SG UBL Invoice

### ISSUE THREAD

**Issue by Sivasgebiz** [phax/phive-rules#18]
<pattern>
	     <rule context="cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory[contains( ' SR SRCA-S SRCA-C ZR SRRC SROVR-RS SROVR-LVG SRLVG ',concat(' ',normalize-space(cbc:ID),' ') ) ] ">
	        <assert test="((//cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/(normalize-space(upper-case(cbc:ID)) = 'GST')]/cbc:CompanyID) or (//cac:TaxRepresentativeParty/cac:PartyTaxScheme[cac:TaxScheme/(normalize-space(upper-case(cbc:ID)) = 'GST')]/cbc:CompanyID))"
                 flag="fatal"
                 id="BR-105-GST-SG">[BR-105-GST-SG]-An Invoice that contains an GST Category code of value SR, SRCA-S, SRCA-C, ZR, SRRC, SROVR-RS, SROVR-LVG or SRLVG  shall  contain the Seller GST identifier (BT-31-GST) or the Seller tax representative GST identifier (BT-63-GST) </assert>
[SG-BIS-Billing3-Schematron.zip](https://github.com/phax/phive-rules/files/12722632/SG-BIS-Billing3-Schematron.zip)

	     </rule>
  </pattern>

**Comment by phax** [comment]
Will be part of the 3.1.2 release
