### ISSUE TITLE
XRechnung PEPPOL-EN16931-R120 has no text

### ISSUE THREAD

**Issue by janwytze** [phax/phive-rules#21]
When I get the PEPPOL-EN16931-R120 error, no text is returned:

https://github.com/phax/phive-rules/blob/b34d05dbdbb1b51262e8733f7440e1487eb40f42/phive-rules-xrechnung/src/main/resources/external/schematron/3.0.2/XRechnung-UBL-validation.xslt#L636

In the Mustang schematron I do see the text:

https://github.com/ZUGFeRD/mustangproject/blob/300461a5da07be0b0da0fb58ae50e789611f3be5/validator/src/main/resources/xslt/XR_30/XRechnung-UBL-validation.xslt#L710

**Comment by phax** [comment]
@janwytze  thanks, this really seems to be an issue.
However ,as this is not the authoritative source for the XRechnung rules, I copied your ticket to https://projekte.kosit.org/xrechnung/xrechnung-schematron/-/issues/191 and will close it here.
hth, Philip
